CREATE TABLE rift_valley_data (
    ID INT PRIMARY KEY,
    ReIndex INT,
    LastModifyingDate DATE,
    ObservationDate DATE,
    EstimatedOutbreakDate DATE,
    ReportingDate DATE,
    Confidentiality VARCHAR(10),
    Latitude DECIMAL(9, 6),j
    Longitude DECIMAL(9, 6),
    adm0_code VARCHAR(10),
    adm0_name VARCHAR(255),
    Locality_name VARCHAR(255),
    Admin1_Name VARCHAR(255),
    Admin1_Descriptor VARCHAR(255),
    Admin1_code VARCHAR(50),
    Admin2_Name VARCHAR(255),
    Admin2_Descriptor VARCHAR(255),
    Admin2_code VARCHAR(50),
    Country VARCHAR(255),
    Region VARCHAR(255),
    Animal_Species TEXT,
    DomesticAnimals INT,
    Wildlife INT,
    Captive INT,
    Production_System VARCHAR(255),
    Status VARCHAR(50),
    Tracking VARCHAR(10),
    Disease VARCHAR(255),
    Diagnosis_Source VARCHAR(255),
    LocalityQuality VARCHAR(50),
    Locality_Source VARCHAR(255),
    Epidemiology_Comments TEXT,
    Humans_Affected VARCHAR(10),
    Num_humans_affected INT,
    Num_Human_Deaths INT,
    At_risk INT,
    Cases INT,
    Deaths INT,
    Destroyed INT,
    Slaughtered INT,
    Vaccinated INT,
    Base_of_diagnosis VARCHAR(255),
    Report_year INT,
    Report_month INT,
    Report_week INT,
    Obs_year INT,
    Obs_month INT,
    Obs_week INT,
    SourceTable VARCHAR(50)
);